### ISSUE TITLE
前端没法启动

### ISSUE THREAD

**Issue by yangfjiahl** [Meituan-Dianping/Zebra#42]
node：v10.16.0
npm：6.13.1

$ npm run dev

> zebra-admin-web@1.0.0 dev /Users/calvin/prj/github/Zebra/zebra-admin-web/src/main/webapp/app
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zebra-admin-web@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zebra-admin-web@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

10 silly lifecycle zebra-admin-web@1.0.0~dev: Args: [ '-c',
10 silly lifecycle   'webpack-dev-server --inline --progress --config build/webpack.dev.conf.js' ]
11 silly lifecycle zebra-admin-web@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle zebra-admin-web@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: zebra-admin-web@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid zebra-admin-web@1.0.0
1

**Comment by daiqiang** [comment]
我也是没法启动 npm install都会报错

**Comment by 8wy1985659** [comment]
install 之后是否提示有冲突？

**Comment by yangfjiahl** [comment]
我这边install 没error，只有warn。
run dev无法启动

$ npm install
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN stylus-loader@3.0.2 requires a peer of stylus@>=0.52.4 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-cli@3.3.10 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.7.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.9.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

up to date in 7.944s

10 packages are looking for funding
  run `npm fund` for details
